#pragma once

#include "raylib.h"

struct ColorScheme
{
	Color CONTROL_PANEL_COLOR;
	Color CARD_COLOR;
	Color SELECTED_CARD_COLOR;
	Color BACKGROUND_COLOR;
	Color SELECTED_TILE_COLOR;
	Color ELIXIR_BAR_COLOR;
	Color ELIXIR_COLOR;
	Color ELIXIR_DIVISORS_COLOR;
};

const ColorScheme LightTheme = {
	.CONTROL_PANEL_COLOR = WHITE,
	.CARD_COLOR = RED,
	.SELECTED_CARD_COLOR = BLUE,
	.BACKGROUND_COLOR = BLACK,
	.SELECTED_TILE_COLOR = SKYBLUE,
	.ELIXIR_BAR_COLOR = WHITE,
	.ELIXIR_COLOR = PINK,
	.ELIXIR_DIVISORS_COLOR = BLACK
};

const ColorScheme RoyaleTheme = {
	.CONTROL_PANEL_COLOR = GRAY,
	.CARD_COLOR = LIGHTGRAY,
	.SELECTED_CARD_COLOR = RED,
	.BACKGROUND_COLOR = WHITE,
	.SELECTED_TILE_COLOR = SKYBLUE,
	.ELIXIR_BAR_COLOR = LIGHTGRAY,
	.ELIXIR_COLOR = PINK,
	.ELIXIR_DIVISORS_COLOR = BLACK
};

static ColorScheme UIColorScheme = RoyaleTheme;