#pragma once

#include "Node.hpp"
#include "event.hpp"
#include <memory>

namespace ui
{
	class Scene : public Node
	{
	protected:
		std::vector<std::unique_ptr<royale::Event>> mGameEvents{};

	public:
		Scene(Rectangle rectangle)
			:
			Node(rectangle)
		{
		}

		//
		//	Generates events from input and passes them to children
		//	This function should not generally be overriden, but if an 
		//	is requiered, call to this function implementation is probably a good idea
		//
		virtual void handleInput();

		//
		//	Return royale events generated by the scene
		//
		std::vector<std::unique_ptr<royale::Event>> pollEvents()
		{
			return std::move(mGameEvents);
		}
	};
}